// Short-form aliases for prefix commands (e.g. "c!inv" / "c!i" both resolve to
// /inventory). Slash commands are unaffected — Discord's command picker only
// ever shows the real name; these are looked up in messageCreate.ts's prefix
// handler after an exact command-name match fails. Keys must stay unique and
// must never collide with a real command name (checked when adding new ones).
export const PREFIX_ALIASES: Record<string, string> = {
  p:    "profile",    pro:   "profile",
  i:    "inventory",  inv:   "inventory",
  c:    "character",  char:  "character",
  ec:   "echoes",     echos: "echoes",
  ee:   "echo-equip",
  eu:   "echo-upgrade",
  er:   "echo-reveal",
  err:  "echo-reroll",
  ed:   "echo-discard",
  el:   "echo-lock",
  ep:   "echo-preset",
  w:    "weapons",    wpns:  "weapons",
  wp:   "weapon",
  wu:   "weapon-upgrade",
  wr:   "weapon-refine",
  wd:   "weapon-discard",
  eq:   "equip",
  st:   "stats",
  asc:  "ascend",
  b:    "boss",
  d:    "dungeon",    dun:   "dungeon",
  du:   "duel",
  r:    "raid",
  fb:   "field-boss",
  t:    "team",
  sh:   "shop",
  wi:   "wish",
  v:    "vote",
  g:    "guide",
  h:    "help",
  dl:   "daily",
  lb:   "leaderboard", top: "leaderboard",
  disp: "dispatch",
  m:    "mail",
  bd:   "bond",
  bds:  "bonds",
  ab:   "ability",
  aw:   "awaken",
  ev:   "evolve",
  f:    "forge",
  vb:   "vibe",
  elem: "element",
  s:    "start",
  su:   "setup",
  ra:   "refill-aura",
  rra:  "reroll-art",
  pat:  "patron",
  pc:   "patron-code",
  bs:   "botstats",
};
